name: Publish to pub.dev

on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'
      # Release Candidates
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  create-sbom-release-asset:
    name: Create SBOM Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish SBOM to Release Assets
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get

      # Generate changelog
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: gem install github_changelog_generator
      - run: github_changelog_generator -u Workiva -p opentelemetry-dart
      - run: |
          git checkout -b ${{ github.ref_name }}-changelog
          git config user.name "github-actions[bot]"
          git config user.email "<>"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push --set-upstream origin ${{ github.ref_name }}-changelog
      - run: |
          gh pr create --base master --head ${{ github.ref_name }}-changelog \
            --title 'Changelog: ${{ github.ref_name }}' \
            --body 'PR Created by Github Actions. Changelog generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)'

      # Publish to pub.dev
      - name: Publish - dry run
        run: dart pub publish --dry-run --skip-validation
      - name: Publish
        run: dart pub publish -f
