name: Publish to pub.dev

on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'
      # Release Candidates
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Publish - dry run
        run: dart pub publish --dry-run --skip-validation
      - name: Publish
        run: dart pub publish -f
